# Practical_6: Numpy

Exercise 1:

Create a NumPy array of integers from 1 to 10.

In [6]:
import numpy as np
A=np.linspace(1,10,10)
print(A)




[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Exercise 2:

Create a 3x3 NumPy array filled with zeros.

In [110]:
c=np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
b=np.eye(3,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

Exercise 4:

Create a 5x5 identity matrix using NumPy.

In [10]:
B=np.eye(5,5)
B

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
A=np.random.rand(4,4)
A

array([[0.5150401 , 0.27564593, 0.01814154, 0.38219669],
       [0.13122263, 0.4486191 , 0.9788849 , 0.42559816],
       [0.70150362, 0.34090312, 0.20398084, 0.06844184],
       [0.56824775, 0.83373322, 0.80982647, 0.66352454]])

In [13]:
np.random.seed(10)

In [14]:
A=np.random.rand(4,4)
A

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [19]:
A.shape

(4, 4)

In [24]:
A=np.arange((16))
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
A.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
A.dtype

dtype('int64')

In [35]:
B=np.arange(2,101,2)
B

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [34]:
B=[x for x in np.arange(1,101) if x % 2==0]
B

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

Slice a 2D NumPy array to extract a submatrix.


Generate a 6x6 matrix of random integers between 10 and 50.

In [36]:
A=np.random.randint(10,50,(6,6))
A

array([[10, 13, 13, 49, 19, 29],
       [31, 46, 33, 16, 34, 34],
       [22, 11, 48, 49, 33, 34],
       [27, 47, 35, 23, 18, 19],
       [30, 26, 15, 25, 10, 28],
       [45, 34, 39, 29, 29, 24]])

In [60]:
a = np.array([[1,2,], [5,6]])
a
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))



14
3.5
3.5
2.0615528128088303
6
1


In [58]:
a = np.array([[1,2,], [5,6]])
a
[1]
[0]

[0]

Create a NumPy array of 20 random integers and find the index of the maximum value.

In [66]:
A=np.random.rand(20)
A

array([0.86510256, 0.50896896, 0.91672295, 0.92115761, 0.08311249,
       0.27771856, 0.0093567 , 0.84234208, 0.64717414, 0.84138612,
       0.26473016, 0.39782075, 0.55282148, 0.16494046, 0.36980809,
       0.14644176, 0.56961841, 0.70373728, 0.28847644, 0.43328806])

In [67]:
np.max(A)

0.9211576102371998

In [ ]:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [73]:
A= np.eye(3,3)
A

B= np.eye(3,3)
B

A*B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Perform matrix multiplication on two 2D NumPy arrays

In [102]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


Create a NumPy array and reverse its elements.

In [103]:
C = np.array([1, 2, 3, 6, 4, 5])
C


array([1, 2, 3, 6, 4, 5])

In [107]:
res=np.flip(C)
print(res)

[5 4 6 3 2 1]


In [ ]:
Flatten a 2D NumPy array into a 1D array.

In [116]:
b = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
result = b.flatten()
print(result)


[1 2 3 2 4 5 1 2 3]


In [ ]:
Stack two NumPy arrays horizontally.

In [126]:
import numpy as np
A = np.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print (A)

B = np.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print (B)
c = np.hstack((A, B)) 
print (C) 


[[ 1  2  3]
 [-1 -2 -3]]
[[ 4  5  6]
 [-4 -5 -6]]
[1 2 3 6 4 5]


In [ ]:
Split a NumPy array into multiple sub-arrays.

In [129]:

B = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(B, 3)
print(array)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
Generate a random NumPy array and round each element to two decimal places.

In [133]:
c= np.round([1.5, 1.53, 1.23, 3.89]) 
print(c) 


[2. 2. 1. 4.]


Find the unique elements of a NumPy array.

In [2]:
M = np.array([1, 2, 3, 1, 4, 5, 2, 5]) 
unique_elements = np.unique(M) 
print(unique_elements) 


[1 2 3 4 5]
